name: lseg
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  auto_route: ^7.7.1

  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  logger: ^1.4.0
  flutter_smart_dialog: ^4.9.0+4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.20
  url_launcher:
  fluttertoast: ^8.2.2
  connectivity: ^3.0.6
  # Upload Image by Camera and Gallery
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  #  Share us Page
  flutter_share: ^2.0.0

  intl: ^0.18.1
  dropdown_button2: ^2.3.7
  firebase_core: ^2.15.0

  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  google_sign_in: ^6.1.4
  form_validator: ^2.1.1
  path_provider: ^2.0.15
  flutter_image_compress: ^2.0.4
  unity_ads_plugin: ^0.3.8
  syncfusion_flutter_pdfviewer: ^22.2.8
  excel: ^2.1.0
  search_choices: ^2.2.6
  firebase_remote_config: ^4.2.5
  flutter_widget_from_html: ^0.10.3
  hive: ^2.2.3
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  firebase_crashlytics: ^3.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/
    - raw/
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/dm_sans/DMSans-Regular.ttf
        - asset: fonts/dm_sans/DMSans-Italic.ttf
          style: italic
        - asset: fonts/dm_sans/DMSans-Bold.ttf
          weight: 700

    - family: ABeeZee
      fonts:
        - asset: fonts/abeezee/ABeeZee-Regular.ttf
        - asset: fonts/abeezee/ABeeZee-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
#  image_path: "assets/ic_logo_512x512.png"
  image_path: "assets/ic_learn_n_earn_logo.png"
  min_sdk_android: 21

