// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6BFnR7LnAdjuN99LhvmeIwhbw_hGuzyI',
    appId: '1:477952135910:android:562303e105dd73b763a127',
    messagingSenderId: '477952135910',
    projectId: 'lseg-5363b',
    storageBucket: 'lseg-5363b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbkSUExNZxxQdpYg2fWqLkZ_5vjH9k-w',
    appId: '1:477952135910:ios:7a8dede971b8265763a127',
    messagingSenderId: '477952135910',
    projectId: 'lseg-5363b',
    storageBucket: 'lseg-5363b.appspot.com',
    androidClientId: '477952135910-398qvetsuh3jaq1oa0ejab9kjjvdgiat.apps.googleusercontent.com',
    iosClientId: '477952135910-imqb8f7r91jsiqjr55c9oge030pnc84j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lseg',
  );
}
